spring:
  application:
    name: schedule-api
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1 # 커넥션 유지
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: true   # 지금은 의도적으로 켜둠 (N+1 재현용)

logging:
  level:
    org.hibernate.SQL: debug # ← SQL 문 자체
    org.hibernate.orm.jdbc.bind: trace # ← ? 에 들어간 실제 값
